export type Specialty =
  | "General Dentistry"
  | "Orthodontics"
  | "Pediatric Dentistry"
  | "Endodontics"
  | "Periodontics"
  | "Oral Surgery"
  | "Prosthodontics"
  | "Cosmetic Dentistry";

export type Dentist = {
  id: string;
  slug: string;
  name: string;
  credentials: string;
  specialty: Specialty;
  practiceName: string;
  address: {
    street: string;
    city: string;
    state: string;
    stateCode: string;
    zip: string;
  };
  phone: string;
  email: string;
  website: string;
  rating: number;
  reviewCount: number;
  acceptingNewPatients: boolean;
  yearsExperience: number;
  bio: string;
  education: string[];
  languages: string[];
  insurance: string[];
  hours: { day: string; hours: string }[];
};

export const dentists: Dentist[] = [
  {
    id: "1",
    slug: "sarah-mitchell-new-york-ny",
    name: "Dr. Sarah Mitchell",
    credentials: "DDS",
    specialty: "General Dentistry",
    practiceName: "Mitchell Family Dental",
    address: {
      street: "245 Park Avenue, Suite 1200",
      city: "New York",
      state: "New York",
      stateCode: "NY",
      zip: "10167",
    },
    phone: "(212) 555-0142",
    email: "info@mitchellfamilydental.com",
    website: "mitchellfamilydental.com",
    rating: 4.9,
    reviewCount: 287,
    acceptingNewPatients: true,
    yearsExperience: 15,
    bio: "Dr. Mitchell has been providing comprehensive family dental care in Manhattan for over 15 years. She focuses on preventive care and patient comfort.",
    education: ["DDS, Columbia University College of Dental Medicine", "BS Biology, Cornell University"],
    languages: ["English", "Spanish"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "MetLife", "Guardian"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 6:00 PM" },
      { day: "Fri", hours: "8:00 AM – 4:00 PM" },
      { day: "Sat", hours: "9:00 AM – 1:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "2",
    slug: "james-rodriguez-los-angeles-ca",
    name: "Dr. James Rodriguez",
    credentials: "DDS, MS",
    specialty: "Orthodontics",
    practiceName: "Rodriguez Orthodontics",
    address: {
      street: "8920 Wilshire Boulevard, Suite 300",
      city: "Los Angeles",
      state: "California",
      stateCode: "CA",
      zip: "90211",
    },
    phone: "(310) 555-0178",
    email: "hello@rodriguezortho.com",
    website: "rodriguezortho.com",
    rating: 4.8,
    reviewCount: 412,
    acceptingNewPatients: true,
    yearsExperience: 22,
    bio: "Board-certified orthodontist specializing in Invisalign, traditional braces, and complex bite correction for children and adults.",
    education: ["MS Orthodontics, UCLA School of Dentistry", "DDS, USC Herman Ostrow School of Dentistry"],
    languages: ["English", "Spanish"],
    insurance: ["Delta Dental", "Blue Cross Blue Shield", "Cigna", "United Healthcare"],
    hours: [
      { day: "Mon–Fri", hours: "7:30 AM – 5:30 PM" },
      { day: "Sat", hours: "8:00 AM – 2:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "3",
    slug: "emily-chen-chicago-il",
    name: "Dr. Emily Chen",
    credentials: "DMD",
    specialty: "Pediatric Dentistry",
    practiceName: "Little Smiles Pediatric Dental",
    address: {
      street: "1455 North Milwaukee Avenue",
      city: "Chicago",
      state: "Illinois",
      stateCode: "IL",
      zip: "60622",
    },
    phone: "(312) 555-0193",
    email: "smile@littlesmileschicago.com",
    website: "littlesmileschicago.com",
    rating: 5.0,
    reviewCount: 521,
    acceptingNewPatients: true,
    yearsExperience: 12,
    bio: "Dr. Chen creates a fun, welcoming environment so kids feel comfortable from their very first visit through their teenage years.",
    education: ["Pediatric Residency, Children's Hospital of Chicago", "DMD, University of Pennsylvania"],
    languages: ["English", "Mandarin"],
    insurance: ["Delta Dental", "Aetna", "Humana", "BCBS"],
    hours: [
      { day: "Mon, Wed, Fri", hours: "8:00 AM – 5:00 PM" },
      { day: "Tue, Thu", hours: "9:00 AM – 6:00 PM" },
      { day: "Sat", hours: "9:00 AM – 12:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "4",
    slug: "michael-thompson-houston-tx",
    name: "Dr. Michael Thompson",
    credentials: "DDS",
    specialty: "Endodontics",
    practiceName: "Thompson Endodontic Specialists",
    address: {
      street: "6624 Fannin Street, Suite 2100",
      city: "Houston",
      state: "Texas",
      stateCode: "TX",
      zip: "77030",
    },
    phone: "(713) 555-0156",
    email: "office@thompsonendo.com",
    website: "thompsonendo.com",
    rating: 4.7,
    reviewCount: 198,
    acceptingNewPatients: false,
    yearsExperience: 18,
    bio: "Endodontic specialist focused on root canal therapy and saving natural teeth using the latest microscopic techniques.",
    education: ["Endodontic Residency, University of Texas Health Science Center", "DDS, Baylor College of Dentistry"],
    languages: ["English"],
    insurance: ["Delta Dental", "Cigna", "MetLife", "Guardian", "Principal"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 1:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "5",
    slug: "jessica-patel-phoenix-az",
    name: "Dr. Jessica Patel",
    credentials: "DDS, MS",
    specialty: "Periodontics",
    practiceName: "Desert Periodontics & Implants",
    address: {
      street: "4350 East Camelback Road, Suite 200",
      city: "Phoenix",
      state: "Arizona",
      stateCode: "AZ",
      zip: "85018",
    },
    phone: "(602) 555-0167",
    email: "info@desertperio.com",
    website: "desertperio.com",
    rating: 4.9,
    reviewCount: 234,
    acceptingNewPatients: true,
    yearsExperience: 14,
    bio: "Specializing in gum disease treatment, dental implants, and gum grafting procedures with a minimally invasive approach.",
    education: ["MS Periodontics, University of Michigan", "DDS, Arizona School of Dentistry"],
    languages: ["English", "Hindi", "Gujarati"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "United Healthcare", "BCBS"],
    hours: [
      { day: "Mon–Fri", hours: "7:00 AM – 4:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "6",
    slug: "david-kim-philadelphia-pa",
    name: "Dr. David Kim",
    credentials: "DMD",
    specialty: "Oral Surgery",
    practiceName: "Philadelphia Oral & Maxillofacial Surgery",
    address: {
      street: "1818 Market Street, Suite 3400",
      city: "Philadelphia",
      state: "Pennsylvania",
      stateCode: "PA",
      zip: "19103",
    },
    phone: "(215) 555-0184",
    email: "contact@philaoralsurgery.com",
    website: "philaoralsurgery.com",
    rating: 4.8,
    reviewCount: 312,
    acceptingNewPatients: true,
    yearsExperience: 20,
    bio: "Oral and maxillofacial surgeon with expertise in wisdom teeth extraction, dental implants, and corrective jaw surgery.",
    education: ["Oral Surgery Residency, Hospital of the University of Pennsylvania", "DMD, Tufts University"],
    languages: ["English", "Korean"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "MetLife", "Independence Blue Cross"],
    hours: [
      { day: "Mon–Fri", hours: "7:30 AM – 5:00 PM" },
      { day: "Sat", hours: "By appointment" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "7",
    slug: "amanda-johnson-san-antonio-tx",
    name: "Dr. Amanda Johnson",
    credentials: "DDS",
    specialty: "General Dentistry",
    practiceName: "Alamo Heights Dental",
    address: {
      street: "5150 Broadway Street",
      city: "San Antonio",
      state: "Texas",
      stateCode: "TX",
      zip: "78209",
    },
    phone: "(210) 555-0129",
    email: "hello@alamoheightsdental.com",
    website: "alamoheightsdental.com",
    rating: 4.6,
    reviewCount: 156,
    acceptingNewPatients: true,
    yearsExperience: 9,
    bio: "Family-focused general dentist offering preventive care, cosmetic services, and same-day crowns using CEREC technology.",
    education: ["DDS, University of Texas Health Science Center at San Antonio"],
    languages: ["English", "Spanish"],
    insurance: ["Delta Dental", "Humana", "Cigna", "MetLife"],
    hours: [
      { day: "Mon, Tue, Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Wed", hours: "10:00 AM – 7:00 PM" },
      { day: "Fri", hours: "8:00 AM – 2:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "8",
    slug: "robert-anderson-san-diego-ca",
    name: "Dr. Robert Anderson",
    credentials: "DDS, MS",
    specialty: "Prosthodontics",
    practiceName: "La Jolla Prosthodontics",
    address: {
      street: "8950 Villa La Jolla Drive, Suite 1200",
      city: "San Diego",
      state: "California",
      stateCode: "CA",
      zip: "92037",
    },
    phone: "(858) 555-0145",
    email: "info@lajollaprostho.com",
    website: "lajollaprostho.com",
    rating: 4.9,
    reviewCount: 178,
    acceptingNewPatients: true,
    yearsExperience: 25,
    bio: "Prosthodontist specializing in full-mouth reconstruction, dental implants, and complex cosmetic cases.",
    education: ["MS Prosthodontics, UCLA", "DDS, UCSF School of Dentistry"],
    languages: ["English"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "Premier Access"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 12:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "9",
    slug: "olivia-martinez-dallas-tx",
    name: "Dr. Olivia Martinez",
    credentials: "DDS",
    specialty: "Cosmetic Dentistry",
    practiceName: "Martinez Smile Studio",
    address: {
      street: "3500 Oak Lawn Avenue, Suite 750",
      city: "Dallas",
      state: "Texas",
      stateCode: "TX",
      zip: "75219",
    },
    phone: "(214) 555-0172",
    email: "concierge@martinezsmiles.com",
    website: "martinezsmiles.com",
    rating: 4.9,
    reviewCount: 389,
    acceptingNewPatients: true,
    yearsExperience: 11,
    bio: "Cosmetic dentist crafting custom veneers, professional whitening, and smile makeovers for clients across DFW.",
    education: ["AACD Accredited", "DDS, Texas A&M College of Dentistry"],
    languages: ["English", "Spanish"],
    insurance: ["Delta Dental", "Cigna", "Most PPO plans"],
    hours: [
      { day: "Tue–Fri", hours: "9:00 AM – 6:00 PM" },
      { day: "Sat", hours: "10:00 AM – 3:00 PM" },
      { day: "Sun–Mon", hours: "Closed" },
    ],
  },
  {
    id: "10",
    slug: "william-davis-san-jose-ca",
    name: "Dr. William Davis",
    credentials: "DDS",
    specialty: "General Dentistry",
    practiceName: "Silicon Valley Dental Group",
    address: {
      street: "2500 Hospital Drive, Building 5",
      city: "San Jose",
      state: "California",
      stateCode: "CA",
      zip: "95128",
    },
    phone: "(408) 555-0118",
    email: "patients@svdentalgroup.com",
    website: "svdentalgroup.com",
    rating: 4.5,
    reviewCount: 245,
    acceptingNewPatients: false,
    yearsExperience: 17,
    bio: "General dentist with deep experience in restorative care, dental crowns, and Invisalign for busy professionals.",
    education: ["DDS, UCSF School of Dentistry"],
    languages: ["English"],
    insurance: ["Delta Dental", "Aetna", "MetLife", "BCBS", "Anthem"],
    hours: [
      { day: "Mon–Fri", hours: "7:00 AM – 7:00 PM" },
      { day: "Sat", hours: "8:00 AM – 2:00 PM" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "11",
    slug: "sophia-brown-austin-tx",
    name: "Dr. Sophia Brown",
    credentials: "DDS",
    specialty: "Pediatric Dentistry",
    practiceName: "Austin Kids Dentistry",
    address: {
      street: "3800 North Lamar Boulevard, Suite 240",
      city: "Austin",
      state: "Texas",
      stateCode: "TX",
      zip: "78756",
    },
    phone: "(512) 555-0163",
    email: "hi@austinkidsdental.com",
    website: "austinkidsdental.com",
    rating: 4.9,
    reviewCount: 367,
    acceptingNewPatients: true,
    yearsExperience: 8,
    bio: "Pediatric dentist passionate about making dental visits stress-free for children of all ages and abilities.",
    education: ["Pediatric Residency, Texas Children's Hospital", "DDS, University of Texas at Houston"],
    languages: ["English"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "Humana", "CHIP/Medicaid"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 3:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "12",
    slug: "christopher-lee-jacksonville-fl",
    name: "Dr. Christopher Lee",
    credentials: "DMD",
    specialty: "General Dentistry",
    practiceName: "Jacksonville Beach Dental",
    address: {
      street: "1925 Beach Boulevard",
      city: "Jacksonville",
      state: "Florida",
      stateCode: "FL",
      zip: "32250",
    },
    phone: "(904) 555-0181",
    email: "info@jaxbeachdental.com",
    website: "jaxbeachdental.com",
    rating: 4.7,
    reviewCount: 203,
    acceptingNewPatients: true,
    yearsExperience: 13,
    bio: "Comprehensive general dentistry with a focus on patient education and long-term oral health.",
    education: ["DMD, University of Florida College of Dentistry"],
    languages: ["English", "Korean"],
    insurance: ["Delta Dental", "Cigna", "MetLife", "Humana", "United Concordia"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 12:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "13",
    slug: "isabella-garcia-columbus-oh",
    name: "Dr. Isabella Garcia",
    credentials: "DDS, MS",
    specialty: "Orthodontics",
    practiceName: "Garcia Orthodontics",
    address: {
      street: "4480 North High Street",
      city: "Columbus",
      state: "Ohio",
      stateCode: "OH",
      zip: "43214",
    },
    phone: "(614) 555-0137",
    email: "smile@garciaortho.com",
    website: "garciaortho.com",
    rating: 4.8,
    reviewCount: 289,
    acceptingNewPatients: true,
    yearsExperience: 10,
    bio: "Orthodontist offering Invisalign, clear aligners, and traditional braces for teens and adults in central Ohio.",
    education: ["MS Orthodontics, Ohio State University", "DDS, Ohio State University College of Dentistry"],
    languages: ["English", "Spanish"],
    insurance: ["Delta Dental", "Aetna", "Cigna", "BCBS Ohio"],
    hours: [
      { day: "Mon, Wed, Thu", hours: "8:30 AM – 5:30 PM" },
      { day: "Tue", hours: "10:00 AM – 7:00 PM" },
      { day: "Fri", hours: "8:00 AM – 2:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "14",
    slug: "matthew-wilson-charlotte-nc",
    name: "Dr. Matthew Wilson",
    credentials: "DDS",
    specialty: "Endodontics",
    practiceName: "Charlotte Endodontic Associates",
    address: {
      street: "1918 Randolph Road, Suite 400",
      city: "Charlotte",
      state: "North Carolina",
      stateCode: "NC",
      zip: "28207",
    },
    phone: "(704) 555-0152",
    email: "office@charlotteendo.com",
    website: "charlotteendo.com",
    rating: 4.7,
    reviewCount: 167,
    acceptingNewPatients: true,
    yearsExperience: 16,
    bio: "Endodontist providing gentle root canal therapy, retreatment, and apical surgery with advanced imaging.",
    education: ["Endodontic Residency, UNC School of Dentistry", "DDS, UNC Chapel Hill"],
    languages: ["English"],
    insurance: ["Delta Dental", "BCBS NC", "Cigna", "MetLife", "United Healthcare"],
    hours: [
      { day: "Mon–Thu", hours: "7:30 AM – 4:30 PM" },
      { day: "Fri", hours: "7:30 AM – 12:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "15",
    slug: "ava-taylor-indianapolis-in",
    name: "Dr. Ava Taylor",
    credentials: "DDS",
    specialty: "General Dentistry",
    practiceName: "Taylor Family Dentistry",
    address: {
      street: "8902 North Meridian Street, Suite 100",
      city: "Indianapolis",
      state: "Indiana",
      stateCode: "IN",
      zip: "46260",
    },
    phone: "(317) 555-0124",
    email: "team@taylorfamilydental.com",
    website: "taylorfamilydental.com",
    rating: 4.8,
    reviewCount: 221,
    acceptingNewPatients: true,
    yearsExperience: 11,
    bio: "Family-focused general dentist serving patients of all ages with preventive, restorative, and cosmetic care.",
    education: ["DDS, Indiana University School of Dentistry"],
    languages: ["English"],
    insurance: ["Delta Dental", "Anthem", "Cigna", "MetLife", "Humana"],
    hours: [
      { day: "Mon, Tue, Thu, Fri", hours: "8:00 AM – 5:00 PM" },
      { day: "Wed", hours: "10:00 AM – 6:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "16",
    slug: "daniel-nguyen-seattle-wa",
    name: "Dr. Daniel Nguyen",
    credentials: "DDS",
    specialty: "Cosmetic Dentistry",
    practiceName: "Emerald City Smile Design",
    address: {
      street: "600 Stewart Street, Suite 1800",
      city: "Seattle",
      state: "Washington",
      stateCode: "WA",
      zip: "98101",
    },
    phone: "(206) 555-0195",
    email: "concierge@emeraldcitysmiles.com",
    website: "emeraldcitysmiles.com",
    rating: 5.0,
    reviewCount: 412,
    acceptingNewPatients: true,
    yearsExperience: 14,
    bio: "Cosmetic dentist specializing in porcelain veneers, professional whitening, and full smile makeovers.",
    education: ["AACD Accredited Fellow", "DDS, University of Washington School of Dentistry"],
    languages: ["English", "Vietnamese"],
    insurance: ["Most major PPOs accepted"],
    hours: [
      { day: "Tue–Fri", hours: "9:00 AM – 6:00 PM" },
      { day: "Sat", hours: "By appointment" },
      { day: "Sun–Mon", hours: "Closed" },
    ],
  },
  {
    id: "17",
    slug: "natalie-clark-denver-co",
    name: "Dr. Natalie Clark",
    credentials: "DDS, MS",
    specialty: "Periodontics",
    practiceName: "Rocky Mountain Periodontal Group",
    address: {
      street: "3300 East 1st Avenue, Suite 590",
      city: "Denver",
      state: "Colorado",
      stateCode: "CO",
      zip: "80206",
    },
    phone: "(303) 555-0149",
    email: "info@rmperio.com",
    website: "rmperio.com",
    rating: 4.8,
    reviewCount: 174,
    acceptingNewPatients: true,
    yearsExperience: 13,
    bio: "Periodontist specializing in dental implants, gum disease treatment, and tissue grafting using minimally invasive techniques.",
    education: ["MS Periodontics, University of Colorado", "DDS, Creighton University"],
    languages: ["English"],
    insurance: ["Delta Dental", "Cigna", "Aetna", "BCBS", "MetLife"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 1:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "18",
    slug: "benjamin-harris-boston-ma",
    name: "Dr. Benjamin Harris",
    credentials: "DMD",
    specialty: "Oral Surgery",
    practiceName: "Back Bay Oral Surgery",
    address: {
      street: "170 Commonwealth Avenue",
      city: "Boston",
      state: "Massachusetts",
      stateCode: "MA",
      zip: "02116",
    },
    phone: "(617) 555-0186",
    email: "appointments@backbayoralsurgery.com",
    website: "backbayoralsurgery.com",
    rating: 4.9,
    reviewCount: 256,
    acceptingNewPatients: true,
    yearsExperience: 19,
    bio: "Oral surgeon offering wisdom teeth removal, implant placement, and reconstructive jaw surgery in a comfortable office setting.",
    education: ["Oral Surgery Residency, Massachusetts General Hospital", "DMD, Harvard School of Dental Medicine"],
    languages: ["English", "French"],
    insurance: ["Delta Dental", "BCBS MA", "Cigna", "Aetna", "Harvard Pilgrim"],
    hours: [
      { day: "Mon–Fri", hours: "8:00 AM – 5:00 PM" },
      { day: "Sat", hours: "By appointment" },
      { day: "Sun", hours: "Closed" },
    ],
  },
  {
    id: "19",
    slug: "grace-walker-portland-or",
    name: "Dr. Grace Walker",
    credentials: "DMD",
    specialty: "General Dentistry",
    practiceName: "Pearl District Dental",
    address: {
      street: "1015 NW Northrup Street",
      city: "Portland",
      state: "Oregon",
      stateCode: "OR",
      zip: "97209",
    },
    phone: "(503) 555-0131",
    email: "hello@pearldistrictdental.com",
    website: "pearldistrictdental.com",
    rating: 4.7,
    reviewCount: 198,
    acceptingNewPatients: false,
    yearsExperience: 7,
    bio: "Holistic general dentist offering mercury-free dentistry, biocompatible materials, and a calming patient experience.",
    education: ["DMD, Oregon Health & Science University"],
    languages: ["English"],
    insurance: ["Delta Dental", "Moda Health", "Cigna", "Regence BCBS"],
    hours: [
      { day: "Mon, Tue, Thu, Fri", hours: "8:00 AM – 5:00 PM" },
      { day: "Wed", hours: "Closed" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
  {
    id: "20",
    slug: "ethan-scott-atlanta-ga",
    name: "Dr. Ethan Scott",
    credentials: "DDS, MS",
    specialty: "Prosthodontics",
    practiceName: "Buckhead Prosthodontic Center",
    address: {
      street: "3525 Piedmont Road NE, Building 8",
      city: "Atlanta",
      state: "Georgia",
      stateCode: "GA",
      zip: "30305",
    },
    phone: "(404) 555-0177",
    email: "info@buckheadprostho.com",
    website: "buckheadprostho.com",
    rating: 4.8,
    reviewCount: 142,
    acceptingNewPatients: true,
    yearsExperience: 21,
    bio: "Prosthodontist specializing in full-mouth rehabilitation, All-on-4 implants, and complex restorative cases.",
    education: ["MS Prosthodontics, Medical College of Georgia", "DDS, Emory University"],
    languages: ["English"],
    insurance: ["Delta Dental", "BCBS Georgia", "Cigna", "Aetna", "MetLife"],
    hours: [
      { day: "Mon–Thu", hours: "8:00 AM – 5:00 PM" },
      { day: "Fri", hours: "8:00 AM – 2:00 PM" },
      { day: "Sat–Sun", hours: "Closed" },
    ],
  },
];

export const allStates = Array.from(
  new Map(dentists.map((d) => [d.address.stateCode, { code: d.address.stateCode, name: d.address.state }])).values()
).sort((a, b) => a.name.localeCompare(b.name));

export const allCities = Array.from(new Set(dentists.map((d) => d.address.city))).sort();

export const allSpecialties: Specialty[] = [
  "General Dentistry",
  "Orthodontics",
  "Pediatric Dentistry",
  "Endodontics",
  "Periodontics",
  "Oral Surgery",
  "Prosthodontics",
  "Cosmetic Dentistry",
];

export function getDentistBySlug(slug: string): Dentist | undefined {
  return dentists.find((d) => d.slug === slug);
}
